[book]
authors = ["Adonis Ling"]
language = "en"
multilingual = false
src = "src"
title = "Algorithm Notes"

[output.html]
no-section-label = true
additional-js = [
	"src/scripts/utils.js",
	"src/scripts/latex.js",
]
